# Generated by Django 5.1.7 on 2025-03-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_alter_student_date_of_birth_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_Bangledeshi',
            field=models.BooleanField(default=True),
        ),
    ]
